--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jhelom/CompassXYZ-plugin-pocketmine
submodule: true
branches:
- master
projects:
  CompassXYZ:
    path: ""
    icon: "assets/icon.png"

...
