name: CompassXYZ
main: Jhelom\CompassXYZ\Main
version: "1.0"
api: ["3.0.0", "3.0.0-ALPHA12"]
load: STARTUP
author: Jhelom
description: Compass XYZ
website: https://github.com/jhelom/CompassXYZ-plugin-pocketmine

permissions:
  jhelom.command.xyz:
    default: default